### ISSUE TITLE
CoreUI update

### ISSUE THREAD

**Issue by AlexZd** [coreui/coreui-vue#87]
Recently I updated CoreUI to latest version (using `npm update`), my `package.json` has following:
```json
"@coreui/coreui-pro": "^3.1.1",
"@coreui/icons": "^1.0.1",
"@coreui/vue": "^3.0.7",
"@coreui/utils": "^1.2.4",
"@coreui/vue-chartjs": "^1.0.5",
```
But when I'm comparing styles with demo project (https://coreui.io/vue/demo/3.0.1) it seems I have different.

For example (copied from Chrome inspector):
My:
```css
.c-wrapper:not(.c-wrapper-fluid) .c-body {
    -webkit-box-flex: 1;
    -ms-flex-positive: 1;
    flex-grow: 1;
}
```
Demo:
```css
.c-wrapper:not(.c-wrapper-fluid) .c-body {
    -webkit-box-orient: vertical;
    -webkit-box-direction: normal;
    -ms-flex-direction: column;
    flex-direction: column;
    overflow-y: auto;
}
.c-body, .c-main {
    -webkit-box-flex: 1;
}
.c-body {
    display: -webkit-box;
    display: -ms-flexbox;
    display: flex;
    -webkit-box-orient: horizontal;
    -webkit-box-direction: normal;
    -ms-flex-direction: row;
    flex-direction: row;
    -ms-flex-positive: 1;
    flex-grow: 1;
}
```

So in my case I don't have `.c-body, .c-main` and `.c-body` css-blocks at all.
Because of this I have some issues, in my case footer does not stick to bottom, because `c-main` block `flex-grow: 1;` does not work, because parent `c-body` not `display: flex`

Do I need to update something else?

Update:
Even some colors not matching:
My:
```css
.c-dark-theme a {
    color: #7267d3;
}
```
Demo:
```css
.c-dark-theme a {
    color: #988fed;
}
```
